DROP TABLE tags;
DROP TABLE rsvps;
DROP TABLE subscribes;
DROP TABLE events;
DROP TABLE users;

CREATE TABLE users (
      uID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
      firstName VARCHAR(50) NOT NULL,
      lastName VARCHAR(50) NOT NULL,
      email VARCHAR(150) NOT NULL,
      password VARCHAR(256) NOT NULL,
      campus VARCHAR(3),
      UNIQUE(email),
      PRIMARY KEY(uID)
);

INSERT INTO users (firstName, lastName, email, password, campus) VALUES ('Test', 'Dummy', 'test.dummy@pomona.edu', 'password1', 'POM');
INSERT INTO users (firstName, lastName, email, password, campus) VALUES ('Marcel', 'Alfonso Garcia', 'magb2017@mymail.pomona.edu', 'password2', 'POM');
INSERT INTO users (firstName, lastName, email, password, campus) VALUES ('Jennifer', 'Zecena', 'zecena22@students.claremontmckenna.edu', 'password3', 'CMC');
INSERT INTO users (firstName, lastName, email, password, campus) VALUES ('Pei Pei', 'Barth Wu', 'mbpa2018@mymail.pomona.edu', 'password4', 'POM');
INSERT INTO users (firstName, lastName, email, password, campus) VALUES ('Hussein', 'Faara', 'hfaa2017@mymail.pomona.edu', 'password5', 'POM');

CREATE TABLE subscribes (
    followerID INT,
    followedID INT,
    PRIMARY KEY(followerID, followedID),
    CONSTRAINT fk_follower FOREIGN KEY(followerID) REFERENCES users(uID),
    CONSTRAINT fk_followed FOREIGN KEY(followedID) REFERENCES users(uID)
);

INSERT INTO subscribes (followerID, followedID) VALUES (1,2);
INSERT INTO subscribes (followerID, followedID) VALUES (1,3);
INSERT INTO subscribes (followerID, followedID) VALUES (1,4);
INSERT INTO subscribes (followerID, followedID) VALUES (2,1);
INSERT INTO subscribes (followerID, followedID) VALUES (2,3);
INSERT INTO subscribes (followerID, followedID) VALUES (2,4);
INSERT INTO subscribes (followerID, followedID) VALUES (3,1);
INSERT INTO subscribes (followerID, followedID) VALUES (3,2);
INSERT INTO subscribes (followerID, followedID) VALUES (3,4);
INSERT INTO subscribes (followerID, followedID) VALUES (4,1);
INSERT INTO subscribes (followerID, followedID) VALUES (4,2);
INSERT INTO subscribes (followerID, followedID) VALUES (4,3);

CREATE TABLE events (
      eID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
      owner INT NOT NULL,
      eventTime TIMESTAMP NOT NULL,
      posterUrl VARCHAR(300) UNIQUE NOT NULL,
      name VARCHAR(160) NOT NULL,
      description TEXT,
      location VARCHAR(200),
      popularity INT NOT NULL,
      status VARCHAR(10),
      PRIMARY KEY(eID),
      UNIQUE(owner,name),
      CONSTRAINT fk_owner FOREIGN KEY(owner) REFERENCES users(uID)
);

INSERT INTO events (owner, eventTime, posterUrl, name, description, location, popularity, status) VALUES (1, '2021-04-16 12:44:51-07', 'no poster', 'Test Event', 'This event is a test, it is not meant to be shown to anyone', 'Big Bridges in Pomona', 0, 'inactive');

CREATE TABLE tags (
    event INT NOT NULL,
    tag VARCHAR(40),
    PRIMARY KEY(event, tag),
    CONSTRAINT fk_tag_owner FOREIGN KEY(event) REFERENCES events(eID)
);

INSERT INTO tags (event, tag) VALUES (1, 'Pomona');
INSERT INTO tags (event, tag) VALUES (1, 'CMC');
INSERT INTO tags (event, tag) VALUES (1, 'HMC');
INSERT INTO tags (event, tag) VALUES (1, 'Scripps');
INSERT INTO tags (event, tag) VALUES (1, 'Pitzer');
INSERT INTO tags (event, tag) VALUES (1, 'Africana Studies');
INSERT INTO tags (event, tag) VALUES (1, 'American Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Anthropology');
INSERT INTO tags (event, tag) VALUES (1, 'Art');
INSERT INTO tags (event, tag) VALUES (1, 'Art History');
INSERT INTO tags (event, tag) VALUES (1, 'Asian American Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Asian Languages & Literatures');
INSERT INTO tags (event, tag) VALUES (1, 'Asian Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Biology');
INSERT INTO tags (event, tag) VALUES (1, 'Chemistry');
INSERT INTO tags (event, tag) VALUES (1, 'Chicana/o-Latina/o Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Chinese');
INSERT INTO tags (event, tag) VALUES (1, 'Classics');
INSERT INTO tags (event, tag) VALUES (1, 'Computer Science');
INSERT INTO tags (event, tag) VALUES (1, 'Economics');
INSERT INTO tags (event, tag) VALUES (1, 'English');
INSERT INTO tags (event, tag) VALUES (1, 'Environmental Analysis');
INSERT INTO tags (event, tag) VALUES (1, 'French');
INSERT INTO tags (event, tag) VALUES (1, 'Gender & Women Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Geology');
INSERT INTO tags (event, tag) VALUES (1, 'German Studies');
INSERT INTO tags (event, tag) VALUES (1, 'History');
INSERT INTO tags (event, tag) VALUES (1, 'International Relations');
INSERT INTO tags (event, tag) VALUES (1, 'Japanese');
INSERT INTO tags (event, tag) VALUES (1, 'Late Antique-Medieval Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Latin American Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Linguistics & Cognitive Science');
INSERT INTO tags (event, tag) VALUES (1, 'Mathematics');
INSERT INTO tags (event, tag) VALUES (1, 'Media Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Middle Eastern Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Molecular Biology');
INSERT INTO tags (event, tag) VALUES (1, 'Music');
INSERT INTO tags (event, tag) VALUES (1, 'Neuroscience');
INSERT INTO tags (event, tag) VALUES (1, 'Philosophy');
INSERT INTO tags (event, tag) VALUES (1, 'Philosophy, Politics & Economics');
INSERT INTO tags (event, tag) VALUES (1, 'Physical Education');
INSERT INTO tags (event, tag) VALUES (1, 'Physics & Astronomy');
INSERT INTO tags (event, tag) VALUES (1, 'Politics');
INSERT INTO tags (event, tag) VALUES (1, 'Psychological Science');
INSERT INTO tags (event, tag) VALUES (1, 'Public Policy Analysis');
INSERT INTO tags (event, tag) VALUES (1, 'Religious Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Romance Languages & Literatures');
INSERT INTO tags (event, tag) VALUES (1, 'Russian');
INSERT INTO tags (event, tag) VALUES (1, 'Russian & Eastern European Studies');
INSERT INTO tags (event, tag) VALUES (1, 'Science, Technology, & Society');
INSERT INTO tags (event, tag) VALUES (1, 'Sociology');
INSERT INTO tags (event, tag) VALUES (1, 'Spanish');
INSERT INTO tags (event, tag) VALUES (1, 'Theatre');
INSERT INTO tags (event, tag) VALUES (1, 'Dance');
INSERT INTO tags (event, tag) VALUES (1, 'Colloquium');
INSERT INTO tags (event, tag) VALUES (1, 'Commencement');
INSERT INTO tags (event, tag) VALUES (1, 'Campus-Wide');
INSERT INTO tags (event, tag) VALUES (1, 'Mandatory');
INSERT INTO tags (event, tag) VALUES (1, 'Important');
INSERT INTO tags (event, tag) VALUES (1, 'Festival');
INSERT INTO tags (event, tag) VALUES (1, 'Concert');
INSERT INTO tags (event, tag) VALUES (1, 'Play');
INSERT INTO tags (event, tag) VALUES (1, 'Relaxation');
INSERT INTO tags (event, tag) VALUES (1, 'Lunch');
INSERT INTO tags (event, tag) VALUES (1, 'Breakfast');
INSERT INTO tags (event, tag) VALUES (1, 'Dinner');
INSERT INTO tags (event, tag) VALUES (1, 'Brunch');
INSERT INTO tags (event, tag) VALUES (1, 'Snack');
INSERT INTO tags (event, tag) VALUES (1, 'Seniors');
INSERT INTO tags (event, tag) VALUES (1, 'Juniors');
INSERT INTO tags (event, tag) VALUES (1, 'Freshmen');
INSERT INTO tags (event, tag) VALUES (1, 'Sophomores');
INSERT INTO tags (event, tag) VALUES (1, 'Outdoors');
INSERT INTO tags (event, tag) VALUES (1, 'Indoors');
INSERT INTO tags (event, tag) VALUES (1, 'OA');
INSERT INTO tags (event, tag) VALUES (1, 'On-Campus');
INSERT INTO tags (event, tag) VALUES (1, 'Off-Campus');
INSERT INTO tags (event, tag) VALUES (1, 'Online');
INSERT INTO tags (event, tag) VALUES (1, 'Talk');
INSERT INTO tags (event, tag) VALUES (1, 'Party');
INSERT INTO tags (event, tag) VALUES (1, 'Guest Speaker/s');

CREATE TABLE rsvps (
    event INT NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    name VARCHAR(100),
    signupTime TIMESTAMP NOT NULL,
    PRIMARY KEY(event, email),
    CONSTRAINT fk_rsvp_event FOREIGN KEY(event) REFERENCES events(eID)
);

INSERT INTO rsvps (event, email, name, signupTime) VALUES (1, 'magb2017@mymail.pomona.edu', 'Marcel Alfonso Garcia', '2021-04-16 14:22:48-07');
INSERT INTO rsvps (event, email, name, signupTime) VALUES (1, 'zecena22@students.claremontmckenna.edu', 'Zecena', '2021-04-16 14:22:48-07');
INSERT INTO rsvps (event, email, name, signupTime) VALUES (1, 'hfaa2017@mymail.pomona.edu', 'Hussein', '2021-04-16 14:22:48-07');
INSERT INTO rsvps (event, email, name, signupTime) VALUES (1, 'mbpa2018@mymail.pomona.edu', '', '2021-04-16 14:22:48-07');
